// The `instructions` field of the MCP server: server-level guidance the host loads
// wholesale and the model reads as "how to use this connector". The main lever for
// getting the brain, and the in-client viewer, invoked at the right moments, since it
// applies across the whole connector rather than one tool at a time.
//
// Here rather than in worker.ts because the local runtime serves the same instructions.
//
// `instructions` is only emitted in the initialize result (SDK server/index.js
// _oninitialize), so it is fixed for the life of a connection. Making it per-brain
// would go stale on switch_brain, like the custom-tool roster does.

export const SERVER_INSTRUCTIONS = `Isomorphic is the user's "brain": a personal or team knowledge base (a GitHub-backed wiki) that can be searched, read, edited, and — importantly — VIEWED inside Claude via the Isomorphic app.

When to reach for it:
- Answer from the brain first for anything specific to this user or their org — their notes, projects, people, decisions, customers. Prefer search_pages / read_page over general knowledge for company- or user-specific questions.
- OPEN THE VIEWER, don't just paste text. Whenever the user wants to look at, explore, or "see" a page, and whenever you cite or reference a specific brain page in an answer, call view_page(path) for that page (or browse_brain for the whole brain). These render the page inside Claude in the Isomorphic app so the user can click through it — far better than a wall of pasted markdown. Treat "I mentioned this page" as a cue to open it.
- Use read_page (not view_page) only when YOU need the raw content to reason over it; use view_page when the goal is for the USER to see it.
- For "what changed", "who edited this", or reviewing recent activity, call view_activity — it opens an audit feed of recent changes (who / what / when); pass a path for one page's history.
- For anything about MEMBERS / the team / the organization's people / org roles / invites, call members. It opens the interactive roster inline (with invite + role controls for admins) and also returns the roster as data, so use it both when the user wants to see or manage people and when YOU need the roster to reason over (e.g. before a role change).
- ACCESS IS PER BRAIN, and it is a DIFFERENT question from org membership. A new brain is PRIVATE to whoever created it: being in the organization does not mean you can open it. So for "who can see / who has access to / who is this brain shared with", call brain_access (it opens the sharing panel inline and returns the list as data); to share one, change what someone can do in it, revoke them, or make it private vs visible to the whole organization, call share_brain. Use members + set_member_role for someone's ORGANIZATION role, and brain_access + share_brain for access to a PARTICULAR brain. Sharing only works for people already in the organization, so invite_member first if they have no account.
- The user may have MULTIPLE brains (personal, team, client). Tools act on the ACTIVE brain by default; call brains to show/switch them, switch_brain to change the active one, or pass \`brain\` to any tool (a name/handle like "acme" or "team wiki") to target a different brain. Opening a brain in the app — view_page / browse_brain / edit_page on a \`brain\` — makes it the ACTIVE brain (the user is now looking at it, and the in-client viewer follows it), so subsequent bare calls stay on it. A one-shot data read (read_page / search_pages with \`brain\`) does NOT change the active brain. WHEN YOU DO NOT KNOW WHICH BRAIN HOLDS SOMETHING, call search_pages with \`scope: "all"\`: it searches every brain the user can reach in one call and every result names the brain it came from. That is the tool for "find this, I am not sure where it is"; without it you would be guessing a brain or searching them one at a time. Keep the default (the active brain) for ordinary searches, and widen only when the question is really about where something lives. If a request could mean a different brain than the active one, target it with \`brain\` or ask which brain. An org admin can adopt another repo as a brain with connect_brain (call it with no repo to see the eligible repos) and remove one with disconnect_brain.
- A CONNECTION IS NOT A BRAIN. When two organizations need to write in the same place (a client engagement, a partner project, a document both sides author), that is create_connection: a shared surface owned by neither of them, with one set of pages that both sides edit. It is not a copy and it is not a share. Reach for it when the other person is OUTSIDE the user's organization; use share_brain when they are inside it. Each side joins the connection to one of its OWN brains, and whoever can reach that brain can reach the room, so nobody ever administers the other organization's people: to add a colleague, add them to the brain the connection hangs off. Call connections to see what a brain is joined to and what invitations are waiting; accept_connection to join one. A connection does not appear in the brain list, because it is a relationship rather than a workspace. Until the far side joins, the room is the initiator's alone to prepare.
- FOLDER NOTES: a folder's overview page must be named \`index.md\` (\`README.md\` is also accepted on older vaults). A page at \`<folder>/index.md\` IS the folder: the app opens it when you click the folder, and okf-view directory listings link folders through it. Any other name (\`overview.md\`, \`vendors.md\`, \`about.md\`) is just a loose page sitting next to its siblings. So when you create a folder of related pages, or the user asks for an overview/index/landing page for a folder, write \`<folder>/index.md\`; and when you find an overview-shaped page under some other name, offer to move_page it to \`index.md\`.
- ONE PAGE = ONE CONCEPT. These brains follow the Open Knowledge Format: anything other pages should be able to link to — a person, vendor, system, event series, project, decision — is its own \`.md\` file with a \`type:\` in its frontmatter. When you are about to write a list of named things as headings or bullets inside one page, stop and write a page per thing instead, then link to them from the parent. A folder note (\`index.md\`) LISTS what is in its folder; it never holds the folder's content inline. The tell that you got this wrong: a reader cannot link to the thing you just wrote, and search cannot return it as a result.
- MATCH THE BRAIN YOU ARE IN. Before adding to an existing folder, look at a sibling page (read_page) and follow what is already there — the same \`type:\` values, the same frontmatter keys, the same granularity. A brain that gives every vendor its own file and then gets one page holding twelve events is worse off than either convention applied consistently. When restructuring, run validate afterwards: it reports structure drift as advisory notes.
- EDIT PART OF A PAGE, don't rewrite it. write_page's \`content\` REPLACES the whole body, so it destroys anything you haven't read. To change part of a page use \`edits\` (exact find/replace, each anchor matching once) or \`append\`: they touch only what you name, need no prior read, and fail loudly rather than guessing. If you do pass \`content\` for an existing page you didn't just write, call read_page first.
- METADATA IS A FIELD WRITE, NOT A REWRITE. Frontmatter is free-form and brain-owned: a brain can track whatever it needs there (\`done\`, \`owner\`, \`due\`, \`priority\`, \`stage\`), and every key becomes filterable by okf-view. To set or remove one, pass write_page's \`fields\` ({key: value}, null to remove). It leaves the body completely untouched, so you never need to read the page first, and it is the right call even when you are changing nothing else. \`title\` / \`type\` / \`description\` / \`status\` have their own arguments and are not settable through \`fields\`.
- IMAGES AND PDFs live in the brain too. To add one, call attach_media with \`url\` and the server downloads it for you: that is the whole call, and it works even for addresses you cannot reach yourself. You cannot supply a file's bytes any other way: for a picture the user attached to the chat, or a file you made yourself with no public URL, ask them to drop it into the Isomorphic panel. To look at an image already in the brain, call read_media and you get the picture itself.
- Write only when asked. Edits to a protected brain open a pull request that merges automatically once checks pass; tell the user the change is on its way rather than exposing git mechanics.
- FEEDBACK ABOUT ISOMORPHIC ITSELF goes to the maintainers with submit_feedback. When the user says something here is broken, confusing, or missing, or asks for a feature, offer to send it rather than only sympathizing. It files a public issue on the project's tracker and needs no GitHub account from them. The first call posts nothing: show them the exact title and body it returns, then call again with \`confirm: true\`. Never file one without the user having seen the text, and never put a token, key, or their private content in it. (Feedback about their own CONTENT is a normal page edit, not this.)
- The brain IS a GitHub repo, and every write tool (write_page, move_page, etc.) already commits to it — that is the only save path; there is no separate "push to GitHub" step. So if the user asks you to push, commit, sync, or save to GitHub, the write tools ARE how you do it (and if you already edited, it is already pushed). Never tell the user you cannot push or commit to GitHub.`;
