// Claude Code hooks for this repository, wired in `.claude/settings.json`. CLAUDE.md
// states these rules to a model; the hooks enforce them on every session.
//
//   node scripts/agent-hooks.ts pre-edit   PreToolUse on Edit/Write: refuses generated
//                                          files and committed migrations
//   node scripts/agent-hooks.ts pre-bash   PreToolUse on Bash: refuses remote D1 writes
//                                          and force-adding ignored deployment files
//   node scripts/agent-hooks.ts stop       Stop: reruns the codegen a change needs, and
//                                          hands the turn back if that changed a file
//
// Each reads the hook's JSON on stdin. Exit 2 blocks, and stderr is what Claude reads.
// Runs under plain `node` (type stripping), not `tsx`: the PreToolUse hooks sit in front
// of every edit and shell command. The deciding functions are pure and pinned by
// `pnpm test:hooks`.

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { isAbsolute, join, relative } from 'node:path';
import { pathToFileURL } from 'node:url';

// ---------- deciding (pure) ----------

/** Why an edit to `path` (repo-relative) is refused, or null to allow it. */
export function refuseEdit(path: string, committed: boolean): string | null {
	if (path === 'wrangler.jsonc') {
		return 'wrangler.jsonc is generated by `pnpm setup:config` from wrangler.template.jsonc. Edit the template, or the value in .dev.vars, and rerun it.';
	}
	if (/\.generated\.tsx?$/.test(path)) {
		return `${path} is generated. Edit its source and run the generator: \`pnpm gen:app\` for the app bundle and view registry, \`pnpm gen:templates\` for brain-template/.`;
	}
	if (/^migrations\/\d{4}_.+\.sql$/.test(path) && committed) {
		return `${path} is committed, so a deployment may already have applied it. Add a new migration with \`pnpm db:migrate:new <name>\` instead.`;
	}
	return null;
}

/** Why a shell command is refused, or null to allow it. */
export function refuseCommand(command: string): string | null {
	for (const segment of command.split(/&&|\|\||[;|\n]/)) {
		if (/\bd1\s+(migrations\s+apply|execute)\b/.test(segment) && /--remote\b/.test(segment)) {
			return 'Remote D1 writes run only in deploy.yml, before the code that needs them ships. Apply locally with `pnpm db:migrate`; production gets the migration on merge.';
		}
		if (
			/\bgit\s+add\b/.test(segment) &&
			/\s(-f|--force)\b/.test(segment) &&
			/(^|[\s/])(wrangler\.jsonc|\.dev\.vars)\b/.test(segment)
		) {
			return "wrangler.jsonc and .dev.vars hold one deployment's identity and secrets. They are gitignored on purpose and never committed.";
		}
	}
	return null;
}

export interface Generator {
	script: string;
	/** The files it writes, repo-relative. */
	outputs: string[];
}

export const GEN_APP: Generator = {
	script: 'gen:app',
	outputs: ['src/lib/app-bundle.generated.ts', 'app/views/registry.generated.ts']
};
export const GEN_TEMPLATES: Generator = {
	script: 'gen:templates',
	outputs: ['src/lib/brain-template.generated.ts']
};

/** The generators a set of changed files (repo-relative) calls for. */
export function generatorsFor(changed: readonly string[]): Generator[] {
	const sources = changed.filter((p) => !/\.generated\.tsx?$/.test(p));
	const out: Generator[] = [];
	// The bundle inlines what app/ imports, including src/lib/ and bundled dependencies.
	if (sources.some((p) => /^(app|src\/lib)\//.test(p) || p === 'pnpm-lock.yaml')) {
		out.push(GEN_APP);
	}
	if (sources.some((p) => p.startsWith('brain-template/'))) out.push(GEN_TEMPLATES);
	return out;
}

// ---------- wiring ----------

interface HookInput {
	cwd?: string;
	stop_hook_active?: boolean;
	tool_input?: { file_path?: string; notebook_path?: string; command?: string };
}

function git(root: string, args: string[]): string[] {
	return execFileSync('git', args, { cwd: root, encoding: 'utf8' }).split('\n').filter(Boolean);
}

function block(reason: string): never {
	process.stderr.write(reason + '\n');
	process.exit(2);
}

function main(mode: string, input: HookInput): void {
	const root = process.env.CLAUDE_PROJECT_DIR || input.cwd || process.cwd();

	if (mode === 'pre-edit') {
		const target = input.tool_input?.file_path ?? input.tool_input?.notebook_path;
		if (!target) return;
		const path = relative(root, isAbsolute(target) ? target : join(root, target));
		if (path.startsWith('..')) return;
		const committed = git(root, ['ls-files', '--', path]).length > 0;
		const reason = refuseEdit(path, committed);
		if (reason) block(reason);
		return;
	}

	if (mode === 'pre-bash') {
		const reason = refuseCommand(input.tool_input?.command ?? '');
		if (reason) block(reason);
		return;
	}

	if (mode === 'stop') {
		// The turn this hook already handed back once: let it end.
		if (input.stop_hook_active) return;
		const changed = [
			...git(root, ['diff', '--name-only', 'HEAD']),
			...git(root, ['ls-files', '--others', '--exclude-standard'])
		];
		const regenerated: string[] = [];
		for (const gen of generatorsFor(changed)) {
			const read = (p: string) =>
				existsSync(join(root, p)) ? readFileSync(join(root, p), 'utf8') : '';
			const before = gen.outputs.map(read);
			try {
				execFileSync('pnpm', ['-s', gen.script], { cwd: root, stdio: 'pipe' });
			} catch (err) {
				const e = err as { stderr?: Buffer; stdout?: Buffer };
				block(
					`\`pnpm ${gen.script}\` failed:\n${String(e.stderr ?? e.stdout ?? err).slice(-2000)}`
				);
			}
			gen.outputs.forEach((p, i) => {
				if (read(p) !== before[i]) regenerated.push(`${p} (pnpm ${gen.script})`);
			});
		}
		if (regenerated.length) {
			block(
				`Regenerated ${regenerated.join(', ')} because its sources changed. It belongs in this change.`
			);
		}
		return;
	}

	throw new Error(`unknown hook mode: ${mode}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	const raw = readFileSync(0, 'utf8');
	main(process.argv[2] ?? '', raw.trim() ? (JSON.parse(raw) as HookInput) : {});
}
