// Codegen: app/ → src/lib/app-bundle.generated.ts
//
// The brain viewer/editor MCP App is served by the Worker as a single
// self-contained ui:// HTML resource (no filesystem at runtime, and the host
// iframe's CSP blocks external hosts — no CDN, no external stylesheet). So we
// bundle at build time and commit the generated module.
//
//   pnpm gen:app
//
// Two build steps, both inlined into app/template.html:
//   1. esbuild bundles app/main.tsx (Preact via preact/compat alias) → one IIFE,
//      injected at the /*APP_JS*/ marker.
//   2. the Tailwind CLI compiles app/styles.css (scanning app/ for classes) → one
//      minified stylesheet, injected at the /*APP_CSS*/ marker.

import { build } from 'esbuild';
import { execFile } from 'node:child_process';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { format, resolveConfig } from 'prettier';

const execFileP = promisify(execFile);

const APP_ENTRY = fileURLToPath(new URL('../app/main.tsx', import.meta.url));
const STYLES = fileURLToPath(new URL('../app/styles.css', import.meta.url));
const TEMPLATE = fileURLToPath(new URL('../app/template.html', import.meta.url));
const CSS_OUT = fileURLToPath(new URL('../app/.tailwind.out.css', import.meta.url));
const OUT_PATH = fileURLToPath(new URL('../src/lib/app-bundle.generated.ts', import.meta.url));
const VIEWS_DIR = fileURLToPath(new URL('../app/views', import.meta.url));
const REGISTRY_OUT = fileURLToPath(new URL('../app/views/registry.generated.ts', import.meta.url));
const ROOT = fileURLToPath(new URL('..', import.meta.url));

// Preact-as-React so shadcn/Radix (and any React-shaped lib) bundle small.
const PREACT_ALIAS = {
	react: 'preact/compat',
	'react-dom': 'preact/compat',
	'react-dom/client': 'preact/compat',
	'react-dom/test-utils': 'preact/test-utils',
	'react/jsx-runtime': 'preact/jsx-runtime',
	'react/jsx-dev-runtime': 'preact/jsx-dev-runtime'
};

function toTemplateLiteral(content: string): string {
	const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
	return `\`${escaped}\``;
}

// Codegen the view-dispatch barrel from app/views/*.tsx. Each routed view file has a
// default `defineView(...)` export; this assembles them into `renderView` and carries
// the compile-time exhaustiveness assertion against the (declaration-merged) View union.
// Written BEFORE esbuild bundles, since app/main.tsx imports it. Prettier-formatted so a
// re-run is byte-stable (git-clean after `pnpm gen:app`).
async function generateRegistry(): Promise<void> {
	const files = (await readdir(VIEWS_DIR))
		.filter(
			(f) => f.endsWith('.tsx') && !f.endsWith('.generated.ts') && !f.endsWith('.generated.tsx')
		)
		.sort();
	// Import identifier = filename base (all view files are valid identifiers today; a
	// non-identifier base would need normalization, but none exists — assert to be safe).
	const entries = files.map((f) => {
		const ident = f.replace(/\.tsx$/, '');
		if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(ident))
			throw new Error(`View filename is not a valid identifier: ${f}`);
		return { ident, file: f };
	});
	const imports = entries.map((e) => `import ${e.ident} from './${e.file}';`).join('\n');
	const list = entries.map((e) => e.ident).join(', ');
	const raw = `// AUTO-GENERATED by scripts/gen-app.ts from app/views/*.tsx. Do not edit by hand.
import type { VNode } from 'preact';
import type { View, ViewAction } from '../core/view-registry.ts';
${imports}

const VIEW_DEFS = [${list}] as const;

// Compile-time exhaustiveness: every View kind must have exactly one renderer.
// A non-\`never\` on either side is a typecheck error below (fix: add the view file
// / augment ViewProps / run \`pnpm gen:app\`).
type Registered = (typeof VIEW_DEFS)[number]['kind'];
type _Missing = Exclude<View['kind'], Registered>;
type _Orphan = Exclude<Registered, View['kind']>;
type _Check = [_Missing] extends [never]
	? [_Orphan] extends [never]
		? true
		: { error: 'renderer registered for a kind not in ViewProps'; orphan: _Orphan }
	: { error: 'no renderer registered for View kind'; missing: _Missing };
const _exhaustive: _Check = true;
void _exhaustive;

const BY_KIND = new Map<string, (view: View) => VNode>(
	VIEW_DEFS.map((d) => [d.kind, d.render as (view: View) => VNode])
);

export function renderView(view: View): VNode {
	const render = BY_KIND.get(view.kind);
	if (!render) throw new Error(\`No view registered for kind: \${(view as { kind: string }).kind}\`);
	return render(view);
}

const ACTIONS_BY_KIND = new Map<string, (view: View) => ViewAction[]>(
	VIEW_DEFS.filter((d) => d.actions).map((d) => [
		d.kind,
		d.actions as unknown as (view: View) => ViewAction[]
	])
);

// What the current view can DO, for the header's right-hand slot. A view with no
// \`actions\` contributes nothing — that is the normal case, not an error, so this
// returns an empty list rather than throwing the way renderView does for a missing
// renderer.
export function viewActions(view: View): ViewAction[] {
	return ACTIONS_BY_KIND.get(view.kind)?.(view) ?? [];
}
`;
	const cfg = (await resolveConfig(REGISTRY_OUT)) ?? {};
	const formatted = await format(raw, { ...cfg, parser: 'typescript' });
	// Write-if-changed: the output is byte-stable, and an unconditional write bumps
	// mtime — which app:dev's watcher on app/ would see, re-triggering gen:app forever.
	const existing = await readFile(REGISTRY_OUT, 'utf8').catch(() => null);
	if (existing === formatted) {
		console.log(`Unchanged ${REGISTRY_OUT} (${entries.length} views).`);
		return;
	}
	await writeFile(REGISTRY_OUT, formatted, 'utf8');
	console.log(`Wrote ${REGISTRY_OUT} (${entries.length} views).`);
}

async function buildJs(): Promise<string> {
	const result = await build({
		entryPoints: [APP_ENTRY],
		bundle: true,
		format: 'iife',
		platform: 'browser',
		target: 'es2022',
		minify: true,
		write: false,
		legalComments: 'none',
		jsx: 'automatic',
		jsxImportSource: 'preact',
		alias: PREACT_ALIAS
	});
	return result.outputFiles[0].text;
}

async function buildCss(): Promise<string> {
	// @tailwindcss/cli ships the `tailwindcss` bin. Run it from the repo root so
	// its @source globs resolve, and minify for the inlined payload.
	await execFileP('pnpm', ['exec', 'tailwindcss', '-i', STYLES, '-o', CSS_OUT, '--minify'], {
		cwd: ROOT
	});
	return readFile(CSS_OUT, 'utf8');
}

async function main(): Promise<void> {
	// Barrel first — app/main.tsx imports it, so esbuild needs it on disk.
	await generateRegistry();
	const [js, css] = await Promise.all([buildJs(), buildCss()]);

	const template = await readFile(TEMPLATE, 'utf8');
	for (const marker of ['/*APP_JS*/', '/*APP_CSS*/']) {
		if (!template.includes(marker))
			throw new Error(`app/template.html is missing the ${marker} marker.`);
	}
	// `</script>` inside the bundle would terminate the inline script tag.
	const safeJs = js.replace(/<\/script>/gi, '<\\/script>');
	// IMPORTANT: replacer FUNCTIONS, never strings — a string replacement makes
	// String.replace interpret `$&`/`$$`/`$1`… in the payload as patterns, which
	// silently corrupted the minified bundle before (see git history).
	const html = template.replace('/*APP_CSS*/', () => css).replace('/*APP_JS*/', () => safeJs);

	const banner = `// GENERATED FILE — do not edit by hand.
// Source: app/*. Regenerate with \`pnpm gen:app\`.
// Self-contained HTML for the brain viewer/editor MCP App (ui:// resource),
// served by the Worker via resources/read.
`;
	await writeFile(
		OUT_PATH,
		banner + '\nexport const BRAIN_APP_HTML = ' + toTemplateLiteral(html) + ';\n',
		'utf8'
	);
	console.log(
		`Wrote ${OUT_PATH} (${(html.length / 1024).toFixed(1)} KiB; js ${(js.length / 1024).toFixed(1)} + css ${(css.length / 1024).toFixed(1)}).`
	);
}

await main();
