// AUTO-GENERATED by scripts/gen-app.ts from app/views/*.tsx. Do not edit by hand.
import type { VNode } from 'preact';
import type { View, ViewAction } from '../core/view-registry.ts';
import ActivityView from './ActivityView.tsx';
import AddBrainView from './AddBrainView.tsx';
import AnalyticsView from './AnalyticsView.tsx';
import BrainAccessView from './BrainAccessView.tsx';
import BrainsView from './BrainsView.tsx';
import Browse from './Browse.tsx';
import ConnectAccountView from './ConnectAccountView.tsx';
import EditView from './EditView.tsx';
import ErrorView from './ErrorView.tsx';
import GraphView from './GraphView.tsx';
import InviteMemberView from './InviteMemberView.tsx';
import LoadingView from './LoadingView.tsx';
import MembersView from './MembersView.tsx';
import PageView from './PageView.tsx';
import SearchView from './SearchView.tsx';
import SettingsView from './SettingsView.tsx';
import ShareBrainView from './ShareBrainView.tsx';

const VIEW_DEFS = [
	ActivityView,
	AddBrainView,
	AnalyticsView,
	BrainAccessView,
	BrainsView,
	Browse,
	ConnectAccountView,
	EditView,
	ErrorView,
	GraphView,
	InviteMemberView,
	LoadingView,
	MembersView,
	PageView,
	SearchView,
	SettingsView,
	ShareBrainView
] as const;

// Compile-time exhaustiveness: every View kind must have exactly one renderer.
// A non-`never` on either side is a typecheck error below (fix: add the view file
// / augment ViewProps / run `pnpm gen:app`).
type Registered = (typeof VIEW_DEFS)[number]['kind'];
type _Missing = Exclude<View['kind'], Registered>;
type _Orphan = Exclude<Registered, View['kind']>;
type _Check = [_Missing] extends [never]
	? [_Orphan] extends [never]
		? true
		: { error: 'renderer registered for a kind not in ViewProps'; orphan: _Orphan }
	: { error: 'no renderer registered for View kind'; missing: _Missing };
const _exhaustive: _Check = true;
void _exhaustive;

const BY_KIND = new Map<string, (view: View) => VNode>(
	VIEW_DEFS.map((d) => [d.kind, d.render as (view: View) => VNode])
);

export function renderView(view: View): VNode {
	const render = BY_KIND.get(view.kind);
	if (!render) throw new Error(`No view registered for kind: ${(view as { kind: string }).kind}`);
	return render(view);
}

const ACTIONS_BY_KIND = new Map<string, (view: View) => ViewAction[]>(
	VIEW_DEFS.filter((d) => d.actions).map((d) => [
		d.kind,
		d.actions as unknown as (view: View) => ViewAction[]
	])
);

// What the current view can DO, for the header's right-hand slot. A view with no
// `actions` contributes nothing — that is the normal case, not an error, so this
// returns an empty list rather than throwing the way renderView does for a missing
// renderer.
export function viewActions(view: View): ViewAction[] {
	return ACTIONS_BY_KIND.get(view.kind)?.(view) ?? [];
}
